module.exports = {
  backend: {
    Java: { d: "", k: "" },
    后端: { d: "", k: "" },
    "Spring Boot": { d: "", k: "" },
    Go: { d: "", k: "" },
    Python: { d: "", k: "" },
    Spring: { d: "", k: "" },
    MySQL: { d: "", k: "" },
    Redis: { d: "", k: "" },
    数据库: { d: "", k: "" },
    算法: { d: "", k: "" },
    架构: { d: "", k: "" },
    JVM: { d: "", k: "" },
    服务器: { d: "", k: "" },
    Linux: { d: "", k: "" },
    设计模式: { d: "", k: "" },
  },
  frontend: {
    JavaScript: { d: "", k: "" },
    前端: { d: "", k: "" },
    "Vue.js": { d: "", k: "" },
    "React.js": { d: "", k: "" },
    CSS: { d: "", k: "" },
    "Node.js": { d: "", k: "" },
    Webpack: { d: "", k: "" },
    面试: { d: "", k: "" },
    微信小程序: { d: "", k: "" },
    TypeScript: { d: "", k: "" },
    Flutter: { d: "", k: "" },
    浏览器: { d: "", k: "" },
    前端框架: { d: "", k: "" },
    GitHub: { d: "", k: "" },
    Promise: { d: "", k: "" },
  },
  android: {
    Android: { d: "", k: "" },
    Flutter: { d: "", k: "" },
    Java: { d: "", k: "" },
    Kotlin: { d: "", k: "" },
    源码: { d: "", k: "" },
    "Android Jetpack": { d: "", k: "" },
    gradle: { d: "", k: "" },
    面试: { d: "", k: "" },
    GitHub: { d: "", k: "" },
    Google: { d: "", k: "" },
    性能优化: { d: "", k: "" },
    开源: { d: "", k: "" },
    架构: { d: "", k: "" },
    RxJava: { d: "", k: "" },
    "Android Studio": { d: "", k: "" },
  },
  ios: {
    iOS: { d: "", k: "" },
    Swift: { d: "", k: "" },
    "Objective-C": { d: "", k: "" },
    Flutter: { d: "", k: "" },
    Apple: { d: "", k: "" },
    OpenGL: { d: "", k: "" },
    SwiftUI: { d: "", k: "" },
    Xcode: { d: "", k: "" },
    GitHub: { d: "", k: "" },
    RxSwift: { d: "", k: "" },
    面试: { d: "", k: "" },
    设计模式: { d: "", k: "" },
    算法: { d: "", k: "" },
    掘金翻译计划: { d: "", k: "" },
    WWDC: { d: "", k: "" },
  },
  ai: {
    人工智能: { d: "", k: "" },
    机器学习: { d: "", k: "" },
    深度学习: { d: "", k: "" },
    算法: { d: "", k: "" },
    Python: { d: "", k: "" },
    神经网络: { d: "", k: "" },
    TensorFlow: { d: "", k: "" },
    NLP: { d: "", k: "" },
    Google: { d: "", k: "" },
    计算机视觉: { d: "", k: "" },
    GitHub: { d: "", k: "" },
    数据分析: { d: "", k: "" },
    掘金翻译计划: { d: "", k: "" },
    架构: { d: "", k: "" },
    Keras: { d: "", k: "" },
  },
  freebie: {
    Git: { d: "", k: "" },
    Linux: { d: "", k: "" },
    GitHub: { d: "", k: "" },
    "Visual Studio Code": { d: "", k: "" },
    前端: { d: "", k: "" },
    Python: { d: "", k: "" },
    Java: { d: "", k: "" },
    程序员: { d: "", k: "" },
    "IntelliJ IDEA": { d: "", k: "" },
    命令行: { d: "", k: "" },
    开源: { d: "", k: "" },
    Chrome: { d: "", k: "" },
    Docker: { d: "", k: "" },
    Serverless: { d: "", k: "" },
    JavaScript: { d: "", k: "" },
  },
  career: {
    程序员: { d: "", k: "" },
    Java: { d: "", k: "" },
    Python: { d: "", k: "" },
    算法: { d: "", k: "" },
    前端: { d: "", k: "" },
    年终总结: { d: "", k: "" },
    后端: { d: "", k: "" },
    代码规范: { d: "", k: "" },
    Linux: { d: "", k: "" },
    编程语言: { d: "", k: "" },
    面试: { d: "", k: "" },
    架构: { d: "", k: "" },
    数据结构: { d: "", k: "" },
    GitHub: { d: "", k: "" },
    设计模式: { d: "", k: "" },
  },
  article: {
    Java: { d: "", k: "" },
    运维: { d: "", k: "" },
    程序员: { d: "", k: "" },
    前端: { d: "", k: "" },
    JavaScript: { d: "", k: "" },
    算法: { d: "", k: "" },
    Python: { d: "", k: "" },
    产品: { d: "", k: "" },
    Linux: { d: "", k: "" },
    面试: { d: "", k: "" },
    Android: { d: "", k: "" },
    数据库: { d: "", k: "" },
    Kubernetes: { d: "", k: "" },
    Flutter: { d: "", k: "" },
    Docker: { d: "", k: "" },
  },
};
